using System.Collections.Generic;
using System.Xml;

namespace BlocklyForHouse.Transform
{
    /// <summary>
    /// Tranformation component for BlocklyForHouse
    /// </summary>
    public class BlocklyTransformer
    {
        /// <summary>
        /// Transform xml text from BlocklyForHouse to Python
        /// </summary>
        /// <param name="text">XML text generated by BlocklyForHouse</param>
        /// <returns>Separate string - Python programs for script installation</returns>
        public IEnumerable<string> XmlToPython(string text)
        {
            var context = new XmlToPython.XmlToPythonContext(text);
            var doc = context.currentNode;
            foreach (XmlNode child in doc.ChildNodes)
            {
                context.currentNode = child;
                yield return (new XmlToPython.Blocks.Script().Interpret(ref context));
            }
        }


        /// <summary>
        /// Add space indention to code
        /// </summary>
        /// <param name="count">lvl of indention</param>
        /// <returns>correct number of spaces</returns>
        public static string AddSpaces(int count)
        {
            return new string(' ', 4 * count);
        }
    }
}
